// 历史股票数据
export const GET_OUT_STOCK_TRANSFERRED = 'GET_OUT_STOCK_TRANSFERRED';
export const UPDATE_STOCK_TRANSFERRED = 'UPDATE_STOCK_TRANSFERRED';
export const SET_OUT_STOCK_HK = 'SET_OUT_STOCK_HK';
export const SET_OUT_STOCK_US = 'SET_OUT_STOCK_US';
export const SET_OUT_MARKET_TYPE = 'SET_OUT_MARKET_TYPE';
export const SET_OUT_MARKET_TYPE_HISTORY = 'SET_OUT_MARKET_TYPE_HISTORY';
export const SET_OUT_SHARES_LIST = 'SET_OUT_SHARES_LIST';
export const UPDATE_OUT_CACHE_DATA_STATUS = 'UPDATE_OUT_CACHE_DATA_STATUS'
export const STOCK_TRANSFER_HISTORY = 'STOCK_TRANSFER_HISTORY'
// export const SET_SEARCH_STOCK_LIST = 'SET_SEARCH_STOCK_LIST';

