// 历史股票数据
export const GET_STOCK_TRANSFERRED = 'GET_STOCK_TRANSFERRED';
export const UPDATE_STOCK_TRANSFERRED = 'UPDATE_STOCK_TRANSFERRED';
export const SET_STOCK_TRANSFERRED_HK = 'SET_STOCK_TRANSFERRED_HK';
export const SET_STOCK_TRANSFERRED_US = 'SET_STOCK_TRANSFERRED_US';
export const SET_ISSHARES = 'SET_ISSHARES';
export const SET_ISHISTORYSHARES = 'SET_ISHISTORYSHARES';
export const SET_SHARES_LIST = 'SET_SHARES_LIST';
export const UPDATE_CACHE_DATA_STATUS = 'UPDATE_CACHE_DATA_STATUS'
// export const SET_SEARCH_STOCK_LIST = 'SET_SEARCH_STOCK_LIST';

