// 历史股票数据
export const GET_STOCK_TRANSFERRED = 'GET_STOCK_TRANSFERRED';
export const UPDATE_STOCK_TRANSFERRED = 'UPDATE_STOCK_TRANSFERRED';
export const SET_ISSHARES = 'SET_ISSHARES';
export const SET_ISHISTORYSHARES = 'SET_ISHISTORYSHARES';

